""" recruiter_fields

Revision ID: c6fe7e863631
Revises: 9cfc54df3e59
Create Date: 2026-05-25 00:39:00.369036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6fe7e863631'
down_revision: Union[str, None] = '9cfc54df3e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_repository_analyses_repo_user', table_name='repository_analyses')
    op.add_column('users', sa.Column('department', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hiring_focus', sa.String(), nullable=True))
    op.add_column('users', sa.Column('security_score_visible', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('high_priority_threshold', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('weight_code_quality', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('weight_security', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('weight_git_activity', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('weight_requirements', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weight_requirements')
    op.drop_column('users', 'weight_git_activity')
    op.drop_column('users', 'weight_security')
    op.drop_column('users', 'weight_code_quality')
    op.drop_column('users', 'high_priority_threshold')
    op.drop_column('users', 'security_score_visible')
    op.drop_column('users', 'hiring_focus')
    op.drop_column('users', 'department')
    op.create_index('uq_repository_analyses_repo_user', 'repository_analyses', ['repository_id', 'user_id'], unique=True)
    # ### end Alembic commands ###
